In [1]:
import os
from glob import glob
from tqdm import tqdm
import pandas as pd

In [2]:
!ls -la 'data/bandung baru/antapani1_22___1202458942.xlsx'

-rw-rw-r-- 1 yurio yurio 96172 Des 10 01:44 'data/bandung baru/antapani1_22___1202458942.xlsx'

In [3]:
# !pip install openpyxl

In [4]:
# !pip install xlrd

In [5]:
pd.read_excel('data/bandung baru/antapani1_22___1202458942.xlsx',engine='openpyxl',header=None)[1:]

,0,1,2,3,4
1,Putra,Kost She House Gatsu Kiaracondong Bandung,Kiaracondong,WiFi · Akses 24 Jam,Rp 500.000
2,Putri,Kost Studiomels Putri Antapani Bandung,Antapani,Akses 24 Jam,Rp 500.000
3,Campur,Kost P Martono Antapani Bandung,Bandung,K. Mandi Dalam,Rp 750.000
4,Campur,Kost Cibodas Raya Tipe A Antapani Bandung,Antapani,K. Mandi Dalam · Akses 24 Jam,Rp 900.000
5,Campur,Kost Ibu Aas Ujung Berung Type D Bandung,Arcamanik,K. Mandi Dalam · Akses 24 Jam,Rp 750.000
...,...,...,...,...,...
456,Campur,Kost Family 261 Kiaracondong Bandung,Kiaracondong,K. Mandi Dalam,Rp 650.000
457,Campur,Kost Yoel Valentino Antapani Bandung,Antapani,K. Mandi Dalam · WiFi · Akses 24 Jam,Rp 650.000
458,Putri,Kost Pak Ahmad Kiaracondong Bandung,Kiaracondong,K. Mandi Dalam · Akses 24 Jam,Rp 650.000
459,Putri,Kost Pondok Nadine Batununggal Bandung,Batununggal,K. Mandi Dalam,Rp 600.000
460,Campur,Kost Bu Suyati Antapani Bandung,Antapani,K. Mandi Dalam · WiFi,Rp 800.000

In [6]:
# def main():
PATH = os.path.join(os.getcwd(),'data')
kotas = [subdir for _ , subdir , _ in os.walk(PATH)][0]

In [7]:
kotas

['surabaya baru',
 'jakarta baru',
 'jogja baru',
 'bandung baru',
 'semarang baru',
 'malang baru']

In [8]:
# read df in each kota
dict_df = {}
for kota in kotas:
    dict_df[kota] = []
    for file in glob(os.path.join(PATH, kota, "*.xls*")):    
#         print(file)
        dict_df[kota].append(pd.read_excel(file,engine='openpyxl',header=None)[1:])

In [9]:
dict_df['surabaya baru'][0]

,0,1,2,3,4
1,Putri,Kost Sumik Wonocolo Surabaya,Wonocolo,NaN,Rp 1.300.000
2,Putri,Kost Pondok Nirwana Merr Tipe C Surabaya,Rungkut,K. Mandi Dalam · WiFi · Akses 24 Jam,Rp 1.600.000
3,Putri,Kost Pondok Nirwana Merr Tipe B Surabaya,Rungkut,WiFi · Akses 24 Jam,Rp 1.500.000
4,Putri,Kost Pondok Nirwana Merr Tipe A Surabaya,Rungkut,WiFi · Akses 24 Jam,Rp 1.400.000
5,Putri,Kost Rungkut Mejoyo Selatan X No 26 Rungkut S...,Rungkut,WiFi · Akses 24 Jam,Rp 1.100.000
...,...,...,...,...,...
576,Putra,Kost Rungkut Tengah 4/4 Surabaya,Gunung Anyar,Akses 24 Jam,Rp 500.000
577,Putra,Kost VIP Merr Tipe D Surabaya,Sukolilo,K. Mandi Dalam · WiFi · Akses 24 Jam,Rp 1.525.000
578,Putra,Kost VIP Merr Tipe B Surabaya,Sukolilo,K. Mandi Dalam · WiFi · Akses 24 Jam,Rp 1.500.000
579,Putra,Kost VIP Merr Tipe C Surabaya,Sukolilo,K. Mandi Dalam · WiFi · Akses 24 Jam,Rp 1.560.000
580,Putra,Kost VIP Merr Tipe E Surabaya,Sukolilo,K. Mandi Dalam · WiFi · Akses 24 Jam,Rp 1.550.000

In [10]:
kotas

['surabaya baru',
 'jakarta baru',
 'jogja baru',
 'bandung baru',
 'semarang baru',
 'malang baru']

In [11]:
# merge df in each kota
dict_df_kota = {}
for kota in kotas:
    df_kota_tmp = pd.DataFrame()
    for df in dict_df[kota]:
        df_kota_tmp = pd.concat([df_kota_tmp,df])
    dict_df_kota[kota] = df_kota_tmp
    dict_df_kota[kota]['kota'] = kota
    dict_df_kota[kota].rename(columns = {0:"texts"}, inplace = True)

In [12]:
dict_df_kota['surabaya baru']

,texts,1,2,3,4,kota
1,Putri,Kost Sumik Wonocolo Surabaya,Wonocolo,NaN,Rp 1.300.000,surabaya baru
2,Putri,Kost Pondok Nirwana Merr Tipe C Surabaya,Rungkut,K. Mandi Dalam · WiFi · Akses 24 Jam,Rp 1.600.000,surabaya baru
3,Putri,Kost Pondok Nirwana Merr Tipe B Surabaya,Rungkut,WiFi · Akses 24 Jam,Rp 1.500.000,surabaya baru
4,Putri,Kost Pondok Nirwana Merr Tipe A Surabaya,Rungkut,WiFi · Akses 24 Jam,Rp 1.400.000,surabaya baru
5,Putri,Kost Rungkut Mejoyo Selatan X No 26 Rungkut S...,Rungkut,WiFi · Akses 24 Jam,Rp 1.100.000,surabaya baru
...,...,...,...,...,...,...
116,Campur,Kost Bandara Juanda Sedati Gede Sidoarjo,Sedati,K. Mandi Dalam · Akses 24 Jam,Rp 600.000,surabaya baru
117,Campur,Kost Davina 2 Tipe B Sedati Sidoarjo,Sedati,K. Mandi Dalam · WiFi · Akses 24 Jam,Rp 900.000,surabaya baru
118,Campur,Kost Davina 2 Tipe A Sedati Sidoarjo,Sedati,K. Mandi Dalam · WiFi · Akses 24 Jam,Rp 750.000,surabaya baru
119,Putri,Kost Bu Agustina Sedati Sidoarjo,Sedati,WiFi · Akses 24 Jam,Rp 1.500.000,surabaya baru
120,Campur,Kost Griya Asri Tipe A Waru Sidoarjo,Waru,K. Mandi Dalam · WiFi · Akses 24 Jam,Rp 1.000.000,surabaya baru

In [13]:
dict_df_kota['jakarta baru']

,texts,1,2,3,4,kota
1,Campur,Kost Kembang Sepatu 32 Tipe B Senen Jakarta Pusat,Senen,NaN,Rp 800.000,jakarta baru
2,Putri,Kost Cha Cha Senen Jakarta Pusat,Senen,K. Mandi Dalam · WiFi,Rp 1.700.000,jakarta baru
3,Campur,Kost Qiwagi Kemayoran Jakarta Pusat,Kemayoran,K. Mandi Dalam,Rp 1.600.000,jakarta baru
4,Campur,Kost GMT Kemayoran Jakarta Pusat,Kemayoran,Akses 24 Jam,Rp 650.000,jakarta baru
5,Putri,Kost Anton Kenari Senen Jakarta Pusat,Senen,Akses 24 Jam,Rp 750.000,jakarta baru
...,...,...,...,...,...,...
4076,Putra,[FLEXI] Kost Singgahsini East 37 Tipe B Tebet ...,Tebet,WiFi · Akses 24 Jam,Rp 2.020.000,jakarta baru
4077,Campur,Kost Rumah Kayu Manis Tipe A Tebet Jakarta Sel...,Tebet,K. Mandi Dalam · WiFi,Rp 2.300.000,jakarta baru
4078,Campur,Kost Bumi Benhil Tipe A Tanah Abang Jakarta Pu...,Tanah Abang,K. Mandi Dalam · WiFi,Rp 3.000.000,jakarta baru
4079,Putra,Kost Benhil 7 Tipe C Tanah Abang Jakarta Pusat GF,Tanah Abang,WiFi,Rp 1.485.000,jakarta baru
4080,Putra,Kost Benhil 7 Tipe A Tanah Abang Jakarta Pusat GF,Tanah Abang,WiFi,Rp 1.620.000,jakarta baru

In [14]:
dict_df_kota['jogja baru']

,texts,1,2,3,4,kota
1,Putri|Penuh,Kost Wisma Aisyah Bantul,Bantul,K. Mandi Dalam · WiFi,|Rp 550.000\n \n/ bulan,jogja baru
2,Putri|Penuh,Kost Khaira Bantul,Bantul,K. Mandi Dalam · WiFi,|Rp 600.000\n \n/ bulan,jogja baru
3,Putri,Kost Aninda II Temon Kulon Progo,Temon,NaN,|Rp 500.000\n \n/ bulan,jogja baru
4,Campur,Kost Omah Wates Yogyakarta,Pengasih,K. Mandi Dalam · Akses 24 Jam,|Rp 1.000.000\n \n/ bulan,jogja baru
5,Putri,[FLEXI] Kost Singgahsini Tessa Tipe B Condongc...,Depok,K. Mandi Dalam · WiFi · Akses 24 Jam,15%\n \nRp\n1.850.000|Rp 1.572.500\n \n/ bulan,jogja baru
...,...,...,...,...,...,...
516,Putri,Kost Wiro Seno Umbulharjo Yogyakarta,Umbulharjo,Akses 24 Jam,|Rp 500.000\n \n/ bulan,jogja baru
517,Putri,Kost Putri New Athena Banguntapan Bantul,Banguntapan,WiFi · Akses 24 Jam,|Rp 500.000\n \n/ bulan,jogja baru
518,Putri,Kost Griya Kelana Pakualaman Yogyakarta,Pakualaman,WiFi · Akses 24 Jam,|Rp 650.000\n \n/ bulan,jogja baru
519,Putri,Kost Putri Kendedes Umbulharjo Yogyakarta,Umbulharjo,K. Mandi Dalam · WiFi,|Rp 850.000\n \n/ bulan,jogja baru
520,Putri,Kost Arika Tipe A Umbulharjo Yogyakarta,Umbulharjo,K. Mandi Dalam · WiFi,|Rp 800.000\n \n/ bulan,jogja baru

In [15]:
dict_df_kota['bandung baru']

,texts,1,2,3,4,kota
1,Campur,Kost Raisa Tipe C Sukajadi Bandung,Sukajadi,K. Mandi Dalam · Akses 24 Jam,Rp 900.000,bandung baru
2,Putri,Kost Peppy Dewi Sartika Bandung,Regol,Akses 24 Jam,Rp 500.000,bandung baru
3,Putri,Kost Saad Tipe B Sumur Bandung,Sumur Bandung,K. Mandi Dalam · WiFi · Akses 24 Jam,Rp 1.050.000,bandung baru
4,Putri,Kost Wanita Pandu Dalam Cicendo Bandung,Cicendo,NaN,Rp 500.000,bandung baru
5,Putra,Kost Balebat Taman Sari Bandung,Bandung Wetan,WiFi,Rp 1.000.000,bandung baru
...,...,...,...,...,...,...
296,NaN,Apartemen M Square Type 2BR Fully Furnished Lt...,Bojongloa Kidul,NaN,Rp 5.000.000,bandung baru
297,NaN,Apartemen M Square Tipe 2BR Fully Furnished LT...,Bojongloa Kidul,NaN,Rp 4.500.000,bandung baru
298,Putri,Kost Pondok Cola Babakan Ciparay Bandung,Babakan Ciparay,WiFi,Rp 2.500.000,bandung baru
299,NaN,Apartemen Mekar Wangi Square Type 2BR Fully Fu...,Bojongloa Kidul,NaN,Rp 4.500.000,bandung baru
300,Campur,KOST JIREH Tipe B Bojongloa Kidul Bandung,Bojongloa Kidul,K. Mandi Dalam · WiFi · Akses 24 Jam,Rp 750.000,bandung baru

In [16]:
dict_df_kota['semarang baru']

,texts,1,2,3,4,kota
1,Putri|Penuh,Kost Ohana Eksklusif Tipe E Semarang Tengah,Semarang Tengah,WiFi · Akses 24 Jam,Rp 850.000,semarang baru
2,Putra|Penuh,Kost Sadewa 5 Semarang Tengah,Semarang Tengah,Akses 24 Jam,Rp 550.000,semarang baru
3,Putra|Penuh,Kost Adama Rejosari Semarang,Semarang Timur,WiFi · Akses 24 Jam,Rp 550.000,semarang baru
4,Putri|Penuh,Kost Via Semarang Tengah,Semarang Tengah,K. Mandi Dalam · WiFi · Akses 24 Jam,Rp 800.000,semarang baru
5,Putri|Penuh,Kost Cita Tipe A Semarang Tengah,Semarang Tengah,WiFi · Akses 24 Jam,Rp 550.000,semarang baru
...,...,...,...,...,...,...
76,Putri,Kost Griya Unggul Gajahmungkur Semarang,Karangmalang,K. Mandi Dalam · WiFi · Akses 24 Jam,Rp 1.200.000,semarang baru
77,Putri,Kost De Ghazlina Gajahmungkur Semarang,Gajahmungkur,K. Mandi Dalam · WiFi,Rp 750.000,semarang baru
78,Putra,Kost Bapak Sarono Tipe A Gajahmungkur Semarang,Gajahmungkur,Akses 24 Jam,Rp 400.000,semarang baru
79,Campur,Kost Bapak Endra Gajahmungkur Semarang,Gajahmungkur,K. Mandi Dalam,Rp 650.000,semarang baru
80,Campur,Kost Wisma Idea Gajahmungkur Semarang,Gajahmungkur,K. Mandi Dalam,Rp 1.200.000,semarang baru

In [17]:
dict_df_kota['malang baru']

,texts,1,2,3,4,kota
1,Campur,Kost Pak Mudjiono Singosari Malang,Singosari,WiFi · Akses 24 Jam,Rp 425.000,malang baru
2,Putra,Kost Biru 2 Singosari Malang,Singosari,Akses 24 Jam,Rp 400.000,malang baru
3,Putra,Kost Karanglo 19C Tipe B Singosari Malang,Singosari,Akses 24 Jam,Rp 425.000,malang baru
4,Putra,Kost Angker Singosari Malang,Singosari,WiFi,Rp 400.000,malang baru
5,Campur,Kost Ibu Tutik Singosari Malang,Singosari,NaN,Rp 400.000,malang baru
...,...,...,...,...,...,...
796,Putri,Kost Griya Asma Tipe B Lowokwaru Malang,Lowokwaru,WiFi · Akses 24 Jam,Rp 550.000,malang baru
797,Putri,Kost Putri Muslim Kertopamuji 6 Lowokwaru Malang,Lowokwaru,WiFi,Rp 700.000,malang baru
798,Putri,Kost Kk Camp Lowokwaru Malang,NaN,K. Mandi Dalam · WiFi · Akses 24 Jam,Rp 850.000,malang baru
799,Putri,Kost Griyashanta C1 Lowokwaru Malang,NaN,WiFi · Akses 24 Jam,Rp 750.000,malang baru
800,Putra,Kost Cozy Putra Lowokwaru Malang,Lowokwaru,K. Mandi Dalam · WiFi · Akses 24 Jam,Rp 1.400.000,malang baru

In [18]:
df_all = pd.DataFrame()

# concat all df from DF_ALL into df_new vertically
for _ , v in dict_df_kota.items():
    df_all = pd.concat([df_all,v])

# df_all = df_all.drop_duplicates()

In [19]:
df_all.rename(columns = {"texts":"jenis_kos",1:"nama_kos",2:"area",3:"fasilitas_kos",4:"harga"}, inplace = True)

In [20]:
df_all = df_all.reset_index(drop=True)

In [21]:
df_all

,jenis_kos,nama_kos,area,fasilitas_kos,harga,kota
0,Putri,Kost Sumik Wonocolo Surabaya,Wonocolo,NaN,Rp 1.300.000,surabaya baru
1,Putri,Kost Pondok Nirwana Merr Tipe C Surabaya,Rungkut,K. Mandi Dalam · WiFi · Akses 24 Jam,Rp 1.600.000,surabaya baru
2,Putri,Kost Pondok Nirwana Merr Tipe B Surabaya,Rungkut,WiFi · Akses 24 Jam,Rp 1.500.000,surabaya baru
3,Putri,Kost Pondok Nirwana Merr Tipe A Surabaya,Rungkut,WiFi · Akses 24 Jam,Rp 1.400.000,surabaya baru
4,Putri,Kost Rungkut Mejoyo Selatan X No 26 Rungkut S...,Rungkut,WiFi · Akses 24 Jam,Rp 1.100.000,surabaya baru
...,...,...,...,...,...,...
49741,Putri,Kost Griya Asma Tipe B Lowokwaru Malang,Lowokwaru,WiFi · Akses 24 Jam,Rp 550.000,malang baru
49742,Putri,Kost Putri Muslim Kertopamuji 6 Lowokwaru Malang,Lowokwaru,WiFi,Rp 700.000,malang baru
49743,Putri,Kost Kk Camp Lowokwaru Malang,NaN,K. Mandi Dalam · WiFi · Akses 24 Jam,Rp 850.000,malang baru
49744,Putri,Kost Griyashanta C1 Lowokwaru Malang,NaN,WiFi · Akses 24 Jam,Rp 750.000,malang baru
49745,Putra,Kost Cozy Putra Lowokwaru Malang,Lowokwaru,K. Mandi Dalam · WiFi · Akses 24 Jam,Rp 1.400.000,malang baru

In [22]:
df_all = df_all.drop_duplicates()

In [23]:
df_all

,jenis_kos,nama_kos,area,fasilitas_kos,harga,kota
0,Putri,Kost Sumik Wonocolo Surabaya,Wonocolo,NaN,Rp 1.300.000,surabaya baru
1,Putri,Kost Pondok Nirwana Merr Tipe C Surabaya,Rungkut,K. Mandi Dalam · WiFi · Akses 24 Jam,Rp 1.600.000,surabaya baru
2,Putri,Kost Pondok Nirwana Merr Tipe B Surabaya,Rungkut,WiFi · Akses 24 Jam,Rp 1.500.000,surabaya baru
3,Putri,Kost Pondok Nirwana Merr Tipe A Surabaya,Rungkut,WiFi · Akses 24 Jam,Rp 1.400.000,surabaya baru
4,Putri,Kost Rungkut Mejoyo Selatan X No 26 Rungkut S...,Rungkut,WiFi · Akses 24 Jam,Rp 1.100.000,surabaya baru
...,...,...,...,...,...,...
48960,Putra,Kost Bu Yudi Griyashanta Tipe A Lowokwaru Malang,Lowokwaru,WiFi,Rp 900.000,malang baru
48961,Putri,Kost Griya Asma Tipe B Lowokwaru Malang,Lowokwaru,WiFi · Akses 24 Jam,Rp 550.000,malang baru
48963,Putri,Kost Kk Camp Lowokwaru Malang,NaN,K. Mandi Dalam · WiFi · Akses 24 Jam,Rp 850.000,malang baru
48964,Putri,Kost Griyashanta C1 Lowokwaru Malang,NaN,WiFi · Akses 24 Jam,Rp 750.000,malang baru
48965,Putra,Kost Cozy Putra Lowokwaru Malang,Lowokwaru,K. Mandi Dalam · WiFi · Akses 24 Jam,Rp 1.400.000,malang baru

In [27]:
df_all = df_all.reset_index(drop=True)

In [28]:
df_all

,jenis_kos,nama_kos,area,fasilitas_kos,harga,kota
0,Putri,Kost Sumik Wonocolo Surabaya,Wonocolo,NaN,Rp 1.300.000,surabaya baru
1,Putri,Kost Pondok Nirwana Merr Tipe C Surabaya,Rungkut,K. Mandi Dalam · WiFi · Akses 24 Jam,Rp 1.600.000,surabaya baru
2,Putri,Kost Pondok Nirwana Merr Tipe B Surabaya,Rungkut,WiFi · Akses 24 Jam,Rp 1.500.000,surabaya baru
3,Putri,Kost Pondok Nirwana Merr Tipe A Surabaya,Rungkut,WiFi · Akses 24 Jam,Rp 1.400.000,surabaya baru
4,Putri,Kost Rungkut Mejoyo Selatan X No 26 Rungkut S...,Rungkut,WiFi · Akses 24 Jam,Rp 1.100.000,surabaya baru
...,...,...,...,...,...,...
1460,Putra,Kost Bu Yudi Griyashanta Tipe A Lowokwaru Malang,Lowokwaru,WiFi,Rp 900.000,malang baru
1461,Putri,Kost Griya Asma Tipe B Lowokwaru Malang,Lowokwaru,WiFi · Akses 24 Jam,Rp 550.000,malang baru
1462,Putri,Kost Kk Camp Lowokwaru Malang,NaN,K. Mandi Dalam · WiFi · Akses 24 Jam,Rp 850.000,malang baru
1463,Putri,Kost Griyashanta C1 Lowokwaru Malang,NaN,WiFi · Akses 24 Jam,Rp 750.000,malang baru
1464,Putra,Kost Cozy Putra Lowokwaru Malang,Lowokwaru,K. Mandi Dalam · WiFi · Akses 24 Jam,Rp 1.400.000,malang baru

In [24]:
!ls

 cat_map_area.json
 cat_map.json
 cat_map_kota.json
 cat_map_type_kos.json
 data
 features.csv
 getkos_model
 getkos_nas.ipynb
 img_notes
 LICENSE
'merged_data - data_choosen.csv'
 model_autokeras
 model_getkos_regression_2020_12_13.tflite
 modeling_get_kos_1.py
 modeling_get_kos.ipynb
 modeling_get_kos.py
 modeling_get_kos_ref_from_autokeras.ipynb
 pre_processing.ipynb
 pre_processing.py
 README.md
 read_merge_dropdup_data.py
 read_n_merge_data.ipynb
 read_n_parse_data_ndfilter.py
 read_n_parse_data.py
 requirements-gpu.txt
 score_map.json
 tflearn_regression.ipynb
 tflearn_regression.py

In [29]:
df_all.to_csv("merged_kota_drop_dupl.csv",index=False)


# if __name__ == '__main__':
#     main()

In [30]:
!ls

 cat_map_area.json
 cat_map.json
 cat_map_kota.json
 cat_map_type_kos.json
 data
 features.csv
 getkos_model
 getkos_nas.ipynb
 img_notes
 LICENSE
'merged_data - data_choosen.csv'
 merged_kota_drop_dupl.csv
 model_autokeras
 model_getkos_regression_2020_12_13.tflite
 modeling_get_kos_1.py
 modeling_get_kos.ipynb
 modeling_get_kos.py
 modeling_get_kos_ref_from_autokeras.ipynb
 pre_processing.ipynb
 pre_processing.py
 README.md
 read_merge_dropdup_data.py
 read_n_merge_data.ipynb
 read_n_parse_data_ndfilter.py
 read_n_parse_data.py
 requirements-gpu.txt
 score_map.json
 tflearn_regression.ipynb
 tflearn_regression.py

In [31]:
pd.read_csv('merged_kota_drop_dupl.csv')

,jenis_kos,nama_kos,area,fasilitas_kos,harga,kota
0,Putri,Kost Sumik Wonocolo Surabaya,Wonocolo,NaN,Rp 1.300.000,surabaya baru
1,Putri,Kost Pondok Nirwana Merr Tipe C Surabaya,Rungkut,K. Mandi Dalam · WiFi · Akses 24 Jam,Rp 1.600.000,surabaya baru
2,Putri,Kost Pondok Nirwana Merr Tipe B Surabaya,Rungkut,WiFi · Akses 24 Jam,Rp 1.500.000,surabaya baru
3,Putri,Kost Pondok Nirwana Merr Tipe A Surabaya,Rungkut,WiFi · Akses 24 Jam,Rp 1.400.000,surabaya baru
4,Putri,Kost Rungkut Mejoyo Selatan X No 26 Rungkut S...,Rungkut,WiFi · Akses 24 Jam,Rp 1.100.000,surabaya baru
...,...,...,...,...,...,...
1460,Putra,Kost Bu Yudi Griyashanta Tipe A Lowokwaru Malang,Lowokwaru,WiFi,Rp 900.000,malang baru
1461,Putri,Kost Griya Asma Tipe B Lowokwaru Malang,Lowokwaru,WiFi · Akses 24 Jam,Rp 550.000,malang baru
1462,Putri,Kost Kk Camp Lowokwaru Malang,NaN,K. Mandi Dalam · WiFi · Akses 24 Jam,Rp 850.000,malang baru
1463,Putri,Kost Griyashanta C1 Lowokwaru Malang,NaN,WiFi · Akses 24 Jam,Rp 750.000,malang baru
1464,Putra,Kost Cozy Putra Lowokwaru Malang,Lowokwaru,K. Mandi Dalam · WiFi · Akses 24 Jam,Rp 1.400.000,malang baru